export const FETCH_POPULAR_MOVIES_REQUEST = 'FETCH_POPULAR_MOVIES_REQUEST';
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS';
export const FETCH_POPULAR_MOVIES_FAILURE = 'FETCH_POPULAR_MOVIES_FAILURE';

export const FETCH_CINEMA_MOVIES_REQUEST = 'FETCH_CINEMA_MOVIES_REQUEST';
export const FETCH_CINEMA_MOVIES_SUCCESS = 'FETCH_CINEMA_MOVIES_SUCCESS';
export const FETCH_CINEMA_MOVIES_FAILURE = 'FETCH_CINEMA_MOVIES_FAILURE';

export const UPDATE_SEARCH_QUERY = 'UPDATE_SEARCH_QUERY';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const FETCH_SEARCH_RESULTS_REQUEST = 'FETCH_SEARCH_RESULTS_REQUEST';
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS';
export const FETCH_SEARCH_RESULTS_FAILURE = 'FETCH_SEARCH_RESULTS_FAILURE';

export const FETCH_MOVIE_INFORMATION_REQUEST = 'FETCH_MOVIE_INFORMATION_REQUEST';
export const FETCH_MOVIE_INFORMATION_SUCCESS = 'FETCH_MOVIE_INFORMATION_SUCCESS';
export const FETCH_MOVIE_INFORMATION_FAILURE = 'FETCH_MOVIE_INFORMATION_FAILURE';
